# Generated by Django 5.2.7 on 2025-11-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_progreso_comunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='fecha_progreso',
            field=models.DateField(auto_now_add=True, default='2025-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progreso',
            name='tiempo_entrenamiento',
            field=models.FloatField(default=2.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progreso',
            name='tipo_ejercicio',
            field=models.CharField(default='ejercicio', max_length=50),
            preserve_default=False,
        ),
    ]
