# Generated by Django 5.2.7 on 2025-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entrenador_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('entrenador', 'Entrenador'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
