# Generated by Django 5.2.7 on 2025-11-24 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comentariocomunidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reto', models.CharField(max_length=50)),
                ('dificultad_reto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=50)),
                ('descripcion_clase', models.TextField(blank=True)),
                ('fecha_clase', models.DateField()),
                ('hora_clase', models.TimeField()),
                ('duracion_clase', models.FloatField()),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entrenador')),
            ],
        ),
    ]
